### GET users from MongoDB
GET http://localhost:3003/api/users

### POST new user to MongoDB
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username" : "DefenderN",
  "name": "Nick",
  "password" : "12345"
  
}

### GET invalid pathway from MongoDB
GET http://localhost:3003/api/userssss

### GET Hello World example Page
GET http://localhost:3003/

### GET all blogs
GET http://localhost:3003/api/blogs

### POST
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Nexxxxw Blog",
            "author": "New Author",
            "url": "http://newblog.com",
            "likes": 10
        }

### POST Blog without title
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Hello world",
  "author": "New Author",
  "likes": 10
        }

### GET single blog
GET http://localhost:3003/api/blogs/664bc7ceddf6667fade80329

### DELETE single blog
DELETE http://localhost:3003/api/blogs/663e324c8b4a0061fb228949

### Update existing blog
PUT http://localhost:3003/api/blogs/6617a992c28515c01010a41a
Content-Type: application/json

{
  "title": "UPDATED BLOG ENTRY NAME",
  "author": "Peter Parker 1",
  "url": "urlplaceholder",
  "likes": 25
}

### POST blog with unique ID
POST http://localhost:3003/api/blogs
Content-Type: application/json

{"_id": "1234567890",
  "title": "Unique ID Blog",
  "author": "New Author",
  "url": "http://newblog.com",
  "likes": 10
}

### Login
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "DefenderN",
  "password": "12345"
}

### Post new blog with updated token
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRlZmVuZGVyTiIsImlkIjoiNjY0YmM1YzFkZGY2NjY3ZmFkZTgwMzEyIiwiaWF0IjoxNzE2MjQyMDUwfQ.fyNzYhdoZxFcINiT_oPYbWrXs1dsCmPqoP2XNMICK_I

{
  "title": "First Token Blog",
  "author": "WUHUAN",
  "url": "http://newblog.com",
  "likes": 101
}

### Delete a post
DELETE http://localhost:3003/api/blogs/664bc7ceddf6667fade80329
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRlZmVuZGVyTiIsImlkIjoiNjY0YmM1YzFkZGY2NjY3ZmFkZTgwMzEyIiwiaWF0IjoxNzE2MjQyMDUwfQ.fyNzYhdoZxFcINiT_oPYbWrXs1dsCmPqoP2XNMICK_I
